// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/get-product-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
var product = {
  name: "Tam Th\u1EA5t Qu\xE2n Nguy\u1EC5n \u2014 Premium Panax Notoginseng Powder",
  description: "Finely milled Panax notoginseng (Tam Th\u1EA5t) powder in gift-ready packaging. Traditional herbal wellness, designed for effortless daily use.",
  variants: [
    { id: "std", label: "Standard Pack", description: "1 Pack", priceUsd: 29.99, note: "" },
    { id: "val", label: "Value Pack", description: "3 Packs", priceUsd: 79.99, note: "Save 10%" },
    { id: "fam", label: "Family Pack", description: "5 Packs", priceUsd: 124.99, note: "Best Value" }
  ],
  badges: ["Traditional Herbal", "Fine Powder", "Gift-Ready", "Daily Wellness"],
  included: "Every order includes a complimentary jar of ginger foot-soak salt.",
  freeShippingThresholdUsd: 75,
  guarantee: "Damaged or incorrect orders replaced within 7 days. Unopened returns accepted within 30 days."
};
var get_product_info_default = defineTool({
  name: "get_product_info",
  title: "Get product info",
  description: "Return the product name, description, variants, pricing, badges, and included add-ons for Tam Th\u1EA5t Qu\xE2n Nguy\u1EC5n.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(product, null, 2) }],
    structuredContent: product
  })
});

// src/lib/mcp/tools/list-faqs.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^4.4.3";
var faqs = [
  { q: "What exactly is Panax notoginseng (Tam Th\u1EA5t)?", a: "Panax notoginseng, known in Vietnamese as Tam Th\u1EA5t, is a traditional herbal root used in Vietnamese and East Asian herbal wellness traditions. Tam Th\u1EA5t Qu\xE2n Nguy\u1EC5n uses it in a finely milled powder form. It is a traditional herbal wellness product and not a medicine." },
  { q: "How do I prepare a serving?", a: "Add one serving of powder to a cup of warm water, stir gently until dissolved, and drink as part of your morning or daily routine. Full instructions are inside every pack." },
  { q: "How is Tam Th\u1EA5t Qu\xE2n Nguy\u1EC5n different from other Tam Th\u1EA5t products online?", a: "We prioritize careful ingredient selection, a fine powder texture, moisture-resistant packaging, and gift-ready presentation rather than competing on price like generic marketplace sellers." },
  { q: "Is this product safe for daily use?", a: "It is intended for daily use by healthy adults as part of a balanced lifestyle. Pregnant, nursing, medicated, or medically managed users should consult their healthcare provider first." },
  { q: "Can I give this as a gift?", a: "Yes \u2014 gifting is a primary use case. Suitable for Lunar New Year, Mid-Autumn Festival, birthdays, retirement, and business appreciation. An optional gift card and ribbon upgrade is available at checkout." },
  { q: "Which pack should I choose?", a: "Standard Pack ($29.99): first-time buyers or a single gift. Value Pack ($79.99, 3 packs): regular use or multiple recipients. Family Pack ($124.99, 5 packs): family routines or corporate gifting." },
  { q: "How long does one pack last?", a: "About 30 days at one serving per day. Exact serving count is printed on the packaging." },
  { q: "What is your return and satisfaction policy?", a: "Damaged or incorrect orders: contact us within 7 days. Unopened returns accepted within 30 days. Opened consumables are generally non-returnable unless there is a quality issue." },
  { q: "How long does shipping take?", a: "Orders dispatch in 1\u20132 business days; delivery in 3\u20135 business days after dispatch. Orders over $75 ship free. Tracking is emailed on dispatch." },
  { q: "Where can I follow Tam Th\u1EA5t Qu\xE2n Nguy\u1EC5n?", a: "Facebook, TikTok, YouTube, and Instagram \u2014 links in the footer of every page." }
];
var list_faqs_default = defineTool2({
  name: "list_faqs",
  title: "List FAQs",
  description: "Return the frequently asked questions and answers shown on the Tam Th\u1EA5t Qu\xE2n Nguy\u1EC5n landing page.",
  inputSchema: {
    search: z.string().optional().describe("Optional case-insensitive substring to filter FAQs by question or answer.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ search }) => {
    const q = search?.trim().toLowerCase();
    const filtered = q ? faqs.filter((f) => f.q.toLowerCase().includes(q) || f.a.toLowerCase().includes(q)) : faqs;
    return {
      content: [{ type: "text", text: JSON.stringify(filtered, null, 2) }],
      structuredContent: { faqs: filtered }
    };
  }
});

// src/lib/mcp/tools/list-reviews.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^4.4.3";
var reviews = [
  { title: "The most thoughtful gift I have given this year.", body: "I bought the Family Pack for my parents during Lunar New Year. The packaging alone made such a strong impression. My mother keeps the box on her shelf. I will be ordering again.", name: "Cristiano Ronaldo", rating: 5 },
  { title: "Finally a Tam Th\u1EA5t product I can trust.", body: "I have tried several products online but always worried about the quality. This one feels completely different from the moment you open it. Clean, professional, and the powder texture is excellent.", name: "Elon Musk", rating: 5 },
  { title: "My clients were genuinely impressed.", body: "I sent these as end-of-year appreciation gifts to three of my business partners. All three reached out specifically to thank me. Highly recommend for corporate gifting.", name: "Business owner", rating: 5 },
  { title: "Simple daily routine, easy to stick to.", body: "I mix it into warm water every morning. Takes thirty seconds. I have kept this habit for two months without skipping.", name: "Vu Phuong Linh", rating: 5 },
  { title: "Worth every dollar for a parent gift.", body: "My father is very particular about herbal products. He said this was one of the cleanest-tasting Tam Th\u1EA5t powders he had tried.", name: "Nguyen Duc Quan", rating: 5 }
];
var list_reviews_default = defineTool3({
  name: "list_reviews",
  title: "List customer reviews",
  description: "Return customer reviews and ratings for Tam Th\u1EA5t Qu\xE2n Nguy\u1EC5n.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("Optional maximum number of reviews to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ limit }) => {
    const out = typeof limit === "number" ? reviews.slice(0, limit) : reviews;
    return {
      content: [{ type: "text", text: JSON.stringify(out, null, 2) }],
      structuredContent: { reviews: out, averageRating: 5 }
    };
  }
});

// src/lib/mcp/tools/get-wellness-guide.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
var guide = {
  title: "Daily Tam Th\u1EA5t Wellness Routine",
  steps: [
    "Add one serving (see pack) of Tam Th\u1EA5t Qu\xE2n Nguy\u1EC5n powder to a cup.",
    "Pour 150\u2013200 ml of warm (not boiling) water over the powder.",
    "Optionally stir in a small teaspoon of honey to taste.",
    "Stir gently until fully dissolved, then drink as part of your morning routine."
  ],
  frequency: "Once per day, ideally in the morning.",
  notes: "Traditional herbal wellness product. Consult a healthcare provider if pregnant, nursing, medicated, or managing a health condition."
};
var get_wellness_guide_default = defineTool4({
  name: "get_wellness_guide",
  title: "Get wellness routine",
  description: "Return the daily preparation and wellness routine for Tam Th\u1EA5t Qu\xE2n Nguy\u1EC5n powder.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(guide, null, 2) }],
    structuredContent: guide
  })
});

// src/lib/mcp/index.ts
var projectRef = "bwliajvzfzfzvakvhuqx";
var mcp_default = defineMcp({
  name: "tam-that-quan-nguyen-mcp",
  title: "Tam Th\u1EA5t Qu\xE2n Nguy\u1EC5n MCP",
  version: "0.1.0",
  instructions: "Tools for the Tam Th\u1EA5t Qu\xE2n Nguy\u1EC5n landing page. Use `get_product_info` for product/pricing, `list_faqs` for FAQs, `list_reviews` for customer reviews, and `get_wellness_guide` for the daily preparation routine.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_product_info_default, list_faqs_default, list_reviews_default, get_wellness_guide_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
